project_id = "zqegcsutpwwrahfiwaic"

[functions.moysklad]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.fetch-external-image]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.create-guest-order]
verify_jwt = false

[functions.ai-customer-assistant]
verify_jwt = false

[functions.create-retail-order]
verify_jwt = false
