project_id = "zqegcsutpwwrahfiwaic"

[functions.moysklad]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.fetch-external-image]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.create-guest-order]
verify_jwt = false

[functions.ai-customer-assistant]
verify_jwt = false

[functions.create-retail-order]
verify_jwt = false

[functions.super-admin-stats]
verify_jwt = false

[functions.ai-seo-generator]
verify_jwt = false

[functions.create-wholesale-order]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.restore-product-images]
verify_jwt = false

[functions.landing-products]
verify_jwt = false

[functions.landing-info-blocks]
verify_jwt = false

[functions.ai-generate-description]
verify_jwt = false
